### PR TITLE
add python lint action

### PR DESCRIPTION
**Pull request by rndmh3ro**

### CODE REVIEW

**Review by schurzi — APPROVED** [review]
why not use ruff?

**Comment by rndmh3ro** [comment]
> why not use ruff?

There's no specific reason, I just happened to start using black for this project.
We can add ruff, too.

**Comment by schurzi** [comment]
> We can add ruff, too.

I was not thinking about adding, but about substituting. Since ruff does the same as black, only faster.

**Comment by rndmh3ro** [comment]
Ruff does a lot more than black, so I'd rather keep these separate.

**Pull request merged**
